apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-secretproviderclass
spec:
  provider: azure
  parameters:
    usePodIdentity: false
    useVMManagedIdentity: true
    userAssignedIdentityID: {{ .Values.keyVault.identity }}
    keyvaultName: {{ .Values.keyVault.name }}
    objects: |
      array:
      {{- range .Values.secrets }}
      - |
        objectName: {{ .name  }}
        objectType: secret
      {{- end }}
      {{- range .Values.certificates }}
      - |
        objectName: {{ .name }}
        objectType: certificate
      {{- end }}
    tenantId: {{ .Values.keyVault.tenantid }}
  secretObjects:                             
  - secretName: sitecore-secrets
    type: Opaque
    data:
    {{- range .Values.secrets }}
    - key: {{ .name }}                          
      objectName: {{ .name  }}                                        
    {{- end }}
    {{- range .Values.certificates }}
    - key: {{ .name }}                          
      objectName: {{ .name  }}                                        
    {{- end }}
    