apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-secretproviderclass
spec:
  provider: azure
  parameters:
    usePodIdentity: false
    useVMManagedIdentity: true
    userAssignedIdentityID: {{ .Values.keyVault.identity }}
    keyvaultName: {{ .Values.keyVault.name }}
    objects: |
      array:
        - |
          objectName: secret1          
          objectType: secret                                      
        - |
          objectName: key1               
          objectType: key

    tenantId: {{ .Values.keyVault.tenantid }}