# Ref - https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret.html
syncSecret:
  enabled: true

windows:
  enabled: true

keyVault:
 identity: "d3a3a8ae-5e9f-4a5b-afe8-e2c8c4a6f3f8"
 name: "sitecore4i9e4"
 tenantid: "3db015b1-2bb5-43d8-a173-007683abc495"
 useVMManagedIdentity: "true"

cd:
  domain: cd.globalhost
  registry: scr.sitecore.com
  image: sxp/sitecore-xm1-cd
  tag: 10.3-ltsc2019
cm:
  domain: cm.globalhost
  registry: scr.sitecore.com
  image: sxp/sitecore-xm1-cm
  tag: 10.3-ltsc2019
id:
  domain: id.globalhost
  registry: scr.sitecore.com
  image: sxp/sitecore-id7
  tag: 10.3-ltsc2019
mssql:
  registry: mcr.microsoft.com
  image: mssql/server
  tag: 2017-CU21-ubuntu-16.04
mssqlInit:
  registry: scr.sitecore.com
  image: sxp/sitecore-xm1-mssql-init
  tag: 10.3-ltsc2019
redis:
  registry: docker.io
  image: redis
  tag: 4.0.14-alpine
solr:
  registry: docker.io
  image: solr
  tag: 8.11.2
solrInit:
  registry: scr.sitecore.com
  image: sxp/sitecore-xm1-solr-init
  tag: 10.3-ltsc2019

# generatorOptions:
#   disableNameSuffixHash: true

# configMapGenerator:
# - name: sitecore-hostnames
#   files:
#   - cd-hostname
#   - cm-hostname
#   - id-hostname

# vars:
# - name: cm-hostname
#   objref:
#     kind: ConfigMap
#     name: sitecore-hostnames
#     apiVersion: v1
#   fieldref:
#     fieldpath: data.cm-hostname
# - name: id-hostname
#   objref:
#     kind: ConfigMap
#     name: sitecore-hostnames
#     apiVersion: v1
#   fieldref:
#     fieldpath: data.id-hostname

# secretGenerator:
# - name: sitecore-admin
#   files:
#   - sitecore-adminpassword.txt
# - name: global-id-tls
#   files:
#     - tls/global-id/tls.key
#     - tls/global-id/tls.crt
#   type: kubernetes.io/tls

